services:
  nginx:
    container_name: cozymeal_case_study_nginx
    networks:
      - network
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx:/etc/nginx/conf.d
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    depends_on:
      - php
      - redis
      - mysql
      - mail

  php:
    container_name: cozymeal_case_study_php
    networks:
      - network
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html:delegated
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}

  mysql:
    image: mysql:8.0
    tty: true
    container_name: cozymeal_case_study_mysql
    networks:
      - network
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cozymeal_case_study_db
      MYSQL_USER: cozymeal_case_study_user
      MYSQL_PASSWORD: cozymeal_case_study_password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  composer:
    container_name: cozymeal_case_study_composer
    networks:
      - network
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  npm:
    image: node:22-alpine
    container_name: cozymeal_case_study_npm
    networks:
      - network
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

  artisan:
    container_name: cozymeal_case_study_artisan
    networks:
      - network
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]

  redis:
    image: redis:alpine
    container_name: cozymeal_case_study_redis
    networks:
      - network
    ports:
      - "6379:6379"

  mail:
    image: mailhog/mailhog:latest
    container_name: cozymeal_case_study_mail
    networks:
      - network
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  network: